[project]
name = "ezassistedcombat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dxcam>=0.0.5",
    "nuitka>=2.8.9",
    "numpy>=2.4.0",
    "pywin32>=311",
]
