[project]
name = "ezassistedcombat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "blp>=0.0.3",
    "pillow>=11.3.0",
    "opencv-python>=4.10.0",
    "pip>=25.2",
    "dxcam>=0.0.5",
]
